### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by evaniswong** [xiaodong-lx/tplink-ipc-control#1]
你好， 可以介绍一下怎么使用吗?

**Comment by xiaodong-lx** [comment]
这是个[HomeAssistant](https://www.home-assistant.io/)自定义组件，使用方法见 [README.md#usage](https://github.com/xiaodong-lx/tplink-ipc-control/blob/main/README.md#usage)，直接调用`tplink_ipc_control.command`服务，填入相应字段即可。

**Comment by mailfarmer** [comment]
能具体举例说明一下吗？对HomeAssistant的服务类要怎么调用不了解啊
