### ISSUE TITLE
这个使用方法有点摸不着头脑

### ISSUE THREAD

**Issue by mailfarmer** [xiaodong-lx/tplink-ipc-control#2]
能具体举例说明一下吗？对HomeAssistant的服务类要怎么调用不了解啊

**Comment by xiaodong-lx** [comment]
可以参考以下文章:
1. [Service calls](https://www.home-assistant.io/docs/scripts/service-calls/)
2. [低成本玩转智能家庭（十二）Home Assistant自动化编写指南（三）](https://zhuanlan.zhihu.com/p/678038699?utm_psn=1799051333032095744)

**Comment by mailfarmer** [comment]
好的，我去学习一下
